### ISSUE TITLE
Process hangs and won't execute

### ISSUE THREAD

**Issue by simon-p-r** [carlos8f/ssh-keygen2#1]
Hi

I followed your examples however the node process hangs and doesn't execute.  Shame as no decent keygen modules with the options you have provided.  Here is failing code, I had to comment out second comment option within opts variable as can't have 2 types of comments within shame object.

var keygen = require('ssh-keygen2');
var assert = require('assert');

var opts = {
        type: 'rsa',
        bits: 4096,
        comment: 'carlos8f',
        passphrase: 'this will encrypt the private key',
        location: '/id_rsa',
        keep: true, // this will keep the resulting files
//      comment: 'optional comment for ssh public key'

};

keygen(opts, function (err, keypair) {
    assert.ifError(err);
    console.log(keypair.private);
    console.log(keypair.public);
    console.log(keypair.fingerprint + '\n');
    console.log(keypair.randomart + '\n');
});

Can I leave passphrase blank/null/undefined without having to override in bash prompt?

Thanks
Simon

**Comment by carlos8f** [comment]
Hi,

Thanks for your interest. I ran your snippet and initially got

```
Error: open /id_rsa failed: Permission denied.
```

Changed location to `/tmp/id_rsa`, and it worked.

The reasons I can think of that the process would hang:
- `location` already exists and `ssh-keygen` is trying to prompt whether an overwrite should occur
- blank argument after the `-N` (passphrase) argument is getting ignored, causing `ssh-keygen` to prompt for a passphrase
- OS difference (I'm running OSX)
- Node difference (I'm running `0.10.29`)
- `ssh-keygen` not installed, or something

Usually when a spawn hangs, I pipe the output so I can see what's going on:

``` js
proc.stderr.on('data', function (data) {
  stderr += data;
});
proc.stderr.pipe(process.stderr); // <--- add this
proc.stdout.on('data', function (data) {
  stdout += data;
});
proc.stdout.pipe(process.stdout); // <--- add this
```

that will probably reveal the issue.

Cheers,
Carlos

**Comment by simon-p-r** [comment]
Thanks Carlos

I am running node 0.10.29 using a Windows 8 machine running git bash (adds ssh-keygen to path), I have played with location and tried various combinations and process still hangs and not as responsive as the ssh-keygen library.  Finally I have discovered you can't silence the passphrase option through the ssh-keygen command.

Cheers
Simon
